# Generated by Django 2.1.7 on 2019-02-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='pripority',
            new_name='priority',
        ),
    ]
