# Generated by Django 2.1.7 on 2019-02-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190212_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='due_time',
            new_name='due_date',
        ),
    ]
